### ISSUE TITLE
Add text size and color editing feature #hackodex2023

### ISSUE THREAD

**Issue by arunsahoo-xt** [arunsahoo-xt/Meme_Generator#1]
Add a text size editor and color picker to choose different colors for text inside meme image and the changes should reflect dynamically

**Comment by sidhartha2002** [comment]
I 'm interested in and I have already fixed the issues and made a pull request. Kindly review it.

**Comment by arunsahoo-xt** [comment]
Sure

**Comment by sidhartha2002** [comment]
**I have fixed tagged issue #1 . 
I have made a pull request and kindly accept and review it .**
